title: "shushank's recent endeavors"
email: "shushanksingh310@gmail.com"
description: shushank’s recent endeavors is a living archive of his explorations, experiments, and everything in between.
baseurl: ""  # Leave empty unless using a project site (e.g., /blog)
url: "https://shushankai.github.io"
twitter_username: "@thisisshushank"
github_username:  "shushankai"

defaults:
  - scope:
      path: ""
    values:
      layout: post

# Build settings
theme: minima
future: true
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
